"""empty message

Revision ID: 07cca3336080
Revises: 6720bdea54fe
Create Date: 2021-04-27 15:53:16.658403

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '07cca3336080'
down_revision = '6720bdea54fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_sessions', sa.Column('followup', sa.String(length=32), nullable=True))
    op.drop_column('student_sessions', 'concerns')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_sessions', sa.Column('concerns', mysql.TEXT(), nullable=True))
    op.drop_column('student_sessions', 'followup')
    # ### end Alembic commands ###
