"""Adds student_notes

Revision ID: 3753b2e815c7
Revises: e973e5d9c384
Create Date: 2020-09-16 19:00:11.962943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3753b2e815c7"
down_revision = "e973e5d9c384"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "student_notes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("student_notes")
    # ### end Alembic commands ###
