"""Add students table

Revision ID: e973e5d9c384
Revises: 0ffc392c7bc2
Create Date: 2020-09-09 23:22:25.268518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e973e5d9c384"
down_revision = "0ffc392c7bc2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "students",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("mentor_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("course", sa.String(length=20), nullable=True),
        sa.Column("stage", sa.String(length=20), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("last_contact", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["mentor_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_students_email"), "students", ["email"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_students_email"), table_name="students")
    op.drop_table("students")
    # ### end Alembic commands ###
